version: "3.8"

services:
  db:
    image: postgres:16  # PostgreSQL 16 вместо 17
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  # Приводим в соответствие с .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
